go_import_path: github.com/redhat-developer/service-binding-operator
sudo: required
dist: xenial
language: go

go:
- 1.13.x

env:
  global:
    - GO111MODULE=on

before_install:
# Install deps
- sudo apt -y install podman

script:
# Run merge-to-master-release
- if [ "$TRAVIS_BRANCH" = "testing-quay" ]; then
  make merge-to-master-release; fi
