apiVersion: apps.openshift.io/v1alpha1
kind: ServiceBindingRequest
metadata:
  name: example-servicebindingrequest
spec:
  backingServiceSelector:
    resourceKind: database.example.org
    resourceVersion: v1alpha1
    resourceRef: mysqldb
  applicationSelector:
    matchLabels:
      connects-to: postgres
      environment: production
    resourceKind: Deployment
